/**
 * Copyright (c) 2010-2011 The Open Source Geospatial Foundation
 *
 * Published under the BSD license.
 * See http://svn.geoext.org/core/trunk/geoext/license.txt for the full text
 * of the license.
 */

/*
 * @requires OSM/Style/Utils.js
 */

OSM.Style.JOSM = {
    getStyleMap: function(styleMap) {
        if (!styleMap) {
            styleMap = new OSM.Style.StyleMap();
            OSM.Style.Utils.addStyle('yellow', styleMap.styles["default"]);
            OSM.Style.Utils.addStyle('blue', styleMap.styles["select"]);
        }

        OSM.Style.Utils.addPointNoLabel(styleMap, 'boundary', 'national_park', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'boundary', 'political', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'boundary', 'civil', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'boundary', 'administrative', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'boundary', 'national', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'route', 'pub_crawl', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'route', 'tour', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'route', 'ski', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'route', 'subsea', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'route', 'ncn', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'route', 'flight', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'route', 'ferry', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'route', 'bus', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'man_made', 'pipeline', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'power', 'minor_line', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'power', 'line', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'railway', 'funicular', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'railway', 'platform', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'railway', 'monorail', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'railway', 'narrow_gauge', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'railway', 'abandoned', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'railway', 'disused', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'railway', 'preserved', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'railway', 'subway', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'railway', 'light_rail', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'railway', 'tram', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'railway', 'rail', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'waterway', 'drain', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'waterway', 'ditch', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'waterway', 'stream', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'waterway', 'canal', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'waterway', 'riverbank', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'waterway', 'river', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'cycleway', 'opposite', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'cycleway', 'opposite_track', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'cycleway', 'track', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'cycleway', 'opposite_lane', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'cycleway', 'lane', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'highway', 'bus_guideway', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'highway', 'pedestrian', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'highway', 'path', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'highway', 'footway', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'highway', 'cycleway', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'highway', 'bridleway', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'highway', 'service', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'highway', 'living_street', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'highway', 'residential', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'highway', 'track', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'highway', 'unsurfaced', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'highway', 'road', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'highway', 'unclassified', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'highway', 'tertiary', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'highway', 'secondary_link', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'highway', 'secondary', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'highway', 'primary_link', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'highway', 'primary', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'highway', 'trunk_link', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'highway', 'trunk', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'highway', 'motorway_link', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'highway', 'motorway', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'barrier', 'retaining_wall', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'barrier', 'city_wall', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'barrier', 'wall', 'app/images/josm/misc/deprecated.png', 16, 16);
        OSM.Style.Utils.addPointNoLabel(styleMap, 'barrier', 'hedge', 'app/images/josm/misc/deprecated.png', 16, 16);

        OSM.Style.Utils.addPoint(styleMap, 'FIXME', '*', 'app/images/josm/fixme.png', 13, 14);
        OSM.Style.Utils.addPoint(styleMap, 'fixme', '*', 'app/images/josm/fixme.png', 13, 14);

        OSM.Style.Utils.addArea(styleMap, 'place', 'islet', '#8de3cb');
        OSM.Style.Utils.addPoint(styleMap, 'place', 'islet', 'app/images/josm/place/islet.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'place', 'island', '#8de3cb');
        OSM.Style.Utils.addPoint(styleMap, 'place', 'island', 'app/images/josm/place/island.png', 16, 14);
        OSM.Style.Utils.addArea(styleMap, 'place', 'locality', '#8de3cb');
        OSM.Style.Utils.addPoint(styleMap, 'place', 'locality', 'app/images/josm/place/locality.png', 16, 12);
        OSM.Style.Utils.addArea(styleMap, 'place', 'suburb', '#8de3cb');
        OSM.Style.Utils.addPoint(styleMap, 'place', 'suburb', 'app/images/josm/place/settlement/town.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'place', 'hamlet', '#8de3cb');
        OSM.Style.Utils.addPoint(styleMap, 'place', 'hamlet', 'app/images/josm/place/settlement/town.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'place', 'village', '#8de3cb');
        OSM.Style.Utils.addPoint(styleMap, 'place', 'village', 'app/images/josm/place/settlement/town.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'place', 'town', '#8de3cb');
        OSM.Style.Utils.addPoint(styleMap, 'place', 'town', 'app/images/josm/place/settlement/town.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'place', 'city', '#8de3cb');
        OSM.Style.Utils.addPoint(styleMap, 'place', 'city', 'app/images/josm/place/settlement/city.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'place', 'county', '#8de3cb');
        OSM.Style.Utils.addPoint(styleMap, 'place', 'county', 'app/images/josm/place/settlement/capital.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'place', 'region', '#8de3cb');
        OSM.Style.Utils.addPoint(styleMap, 'place', 'region', 'app/images/josm/place/settlement/capital.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'place', 'state', '#8de3cb');
        OSM.Style.Utils.addPoint(styleMap, 'place', 'state', 'app/images/josm/place/settlement/capital.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'place', 'country', '#8de3cb');
        OSM.Style.Utils.addPoint(styleMap, 'place', 'country', 'app/images/josm/place/settlement/capital.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'place', 'continent', '#8de3cb');
        OSM.Style.Utils.addPoint(styleMap, 'place', 'continent', 'app/images/josm/place/settlement/capital.png', 16, 16);
        OSM.Style.Utils.addStroke(styleMap, 'mountain_pass', '*', '#ff0000', 4, 'dash');
        OSM.Style.Utils.addPoint(styleMap, 'mountain_pass', '*', 'app/images/josm/misc/landmark/mountain_pass.png', 16, 16);

        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'fishing', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'fishing', 'app/images/josm/sport/fishing.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'archery', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'archery', 'app/images/josm/sport/archery.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'badminton', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'badminton', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'diving', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'diving', 'app/images/josm/sport/diving.png', 5, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'sailing', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'sailing', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'rowing', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'rowing', 'app/images/josm/sport/rowing.png', 16, 15);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'handball', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'handball', 'app/images/josm/sport/handball.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'bowling', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'bowling', 'app/images/josm/sport/10pin.png', 15, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'beachvolleyball', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'beachvolleyball', 'app/images/josm/sport/volleyball.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'volleyball', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'volleyball', 'app/images/josm/sport/volleyball.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'shooting', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'shooting', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'squash', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'squash', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'paintball', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'paintball', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'tennis', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'tennis', 'app/images/josm/sport/tennis.png', 16, 15);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'table_tennis', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'table_tennis', 'app/images/josm/sport/table_tennis.png', 16, 15);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'skiing', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'skiing', 'app/images/josm/sport/skiing.png', 15, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'swimming', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'swimming', 'app/images/josm/sport/pool.png', 16, 11);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'skateboard', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'skateboard', 'app/images/josm/sport/skateboard.png', 16, 5);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'skating', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'skating', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'racquet', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'racquet', 'app/images/josm/sport/racquetball.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'pelota', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'pelota', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'multi', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'multi', 'app/images/josm/sport/multi.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'motor', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'motor', 'app/images/josm/vehicle/motorbike.png', 16, 12);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'horse_racing', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'horse_racing', 'app/images/josm/sport/riding.png', 16, 12);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'hockey', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'hockey', 'app/images/josm/sport/hockey.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'gymnastics', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'gymnastics', 'app/images/josm/sport/multi.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'golf', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'golf', 'app/images/josm/sport/golf.png', 9, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'equestrian', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'equestrian', 'app/images/josm/sport/riding.png', 16, 12);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'dog_racing', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'dog_racing', 'app/images/josm/leisure/dog.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'cycling', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'cycling', 'app/images/josm/sport/cycling.png', 16, 14);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'croquet', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'croquet', 'app/images/josm/sport/croquet.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'cricket_nets', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'cricket_nets', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'cricket', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'cricket', 'app/images/josm/sport/cricket.png', 7, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'climbing', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'climbing', 'app/images/josm/sport/climbing.png', 8, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'chess', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'chess', 'app/images/josm/sport/chess.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'canoe', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'canoe', 'app/images/josm/sport/canoe.png', 15, 5);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'bowls', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'bowls', 'app/images/josm/sport/boule.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'boules', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'boules', 'app/images/josm/sport/boule.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'basketball', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'basketball', 'app/images/josm/sport/basketball.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'baseball', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'baseball', 'app/images/josm/sport/baseball.png', 16, 15);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'rugby_union', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'rugby_union', 'app/images/josm/sport/football.png', 16, 10);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'rugby_league', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'rugby_league', 'app/images/josm/sport/football.png', 16, 10);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'gaelic_football', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'gaelic_football', 'app/images/josm/sport/soccer.png', 16, 15);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'canadian_football', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'canadian_football', 'app/images/josm/sport/soccer.png', 16, 15);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'american_football', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'american_football', 'app/images/josm/sport/soccer.png', 16, 15);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'australian_football', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'australian_football', 'app/images/josm/sport/soccer.png', 16, 15);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'soccer', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'soccer', 'app/images/josm/sport/soccer.png', 16, 15);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', 'athletics', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', 'athletics', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', '10pin', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', '10pin', 'app/images/josm/sport/10pin.png', 15, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'leidure', '*', 'sport', '9pin', '#bde3cb');
        OSM.Style.Utils.addSubPoint(styleMap, 'leidure', '*', 'sport', '9pin', 'app/images/josm/sport/10pin.png', 15, 16);

        OSM.Style.Utils.addStroke(styleMap, 'boundary', 'national_park', '#FF6600', 3, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'boundary', 'political', '#FF6600', 3, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'boundary', 'civil', '#FF6600', 3, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'boundary', 'administrative', '#FF6600', 3, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'boundary', '*', 'admin_level', '10', '#FF6600', 3, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'boundary', '*', 'admin_level', '9', '#FF6600', 3, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'boundary', '*', 'admin_level', '8', '#FF6600', 4, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'boundary', '*', 'admin_level', '7', '#FF6600', 4, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'boundary', '*', 'admin_level', '6', '#FF6600', 6, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'boundary', '*', 'admin_level', '5', '#FF6600', 6, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'boundary', '*', 'admin_level', '4', '#FF6600', 8, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'boundary', '*', 'admin_level', '3', '#FF6600', 8, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'boundary', '*', 'admin_level', '2', '#FF6600', 10, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'boundary', '*', 'admin_level', '1', '#FF6600', 10, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'boundary', 'national', '#FF6600', 3, 'dash');

        OSM.Style.Utils.addStroke(styleMap, 'route', 'pub_crawl', '#809bc0', 3, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'route', 'tour', '#809bc0', 3, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'route', 'ski', '#809bc0', 3, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'route', 'subsea', '#809bc0', 3, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'route', 'ncn', '#809bc0', 3, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'route', 'flight', '#809bc0', 3, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'route', 'ferry', '#809bc0', 3, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'route', 'bus', '#809bc0', 3, 'dash');

        OSM.Style.Utils.addPoint(styleMap, 'natural', 'tree', 'app/images/josm/misc/landmark/trees.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'natural', 'cave_entrance', '#002f00');
        OSM.Style.Utils.addPoint(styleMap, 'natural', 'cave_entrance', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'natural', 'land', '#002f00');
        OSM.Style.Utils.addPoint(styleMap, 'natural', 'land', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'natural', 'bay', '#002f00');
        OSM.Style.Utils.addPoint(styleMap, 'natural', 'bay', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'natural', 'beach', '#f8dba2');
        OSM.Style.Utils.addPoint(styleMap, 'natural', 'beach', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'natural', 'mud', '#cba762');
        OSM.Style.Utils.addPoint(styleMap, 'natural', 'mud', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addStroke(styleMap, 'natural', 'coastline', '#0000ff', 3);
        OSM.Style.Utils.addPoint(styleMap, 'natural', 'coastline', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'natural', 'water', '#0000ff');
        OSM.Style.Utils.addPoint(styleMap, 'natural', 'water', 'app/images/josm/nautical/water.png', 13, 16);
        OSM.Style.Utils.addArea(styleMap, 'natural', 'wetland', '#4f4ff3');
        OSM.Style.Utils.addPoint(styleMap, 'natural', 'wetland', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'natural', 'wood', '#008000');
        OSM.Style.Utils.addPoint(styleMap, 'natural', 'wood', 'app/images/josm/misc/landmark/trees.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'natural', 'heath', '#ffffc0');
        OSM.Style.Utils.addPoint(styleMap, 'natural', 'heath', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'natural', 'fell', '#002f00');
        OSM.Style.Utils.addPoint(styleMap, 'natural', 'fell', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'natural', 'scrub', '#007000');
        OSM.Style.Utils.addPoint(styleMap, 'natural', 'scrub', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'natural', 'scree', '#002f00');
        OSM.Style.Utils.addPoint(styleMap, 'natural', 'scree', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addStrokeArea(styleMap, 'natural', 'cliff', '#002f00', '2');
        OSM.Style.Utils.addPoint(styleMap, 'natural', 'cliff', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'natural', 'volcano', '#5f0000');
        OSM.Style.Utils.addPoint(styleMap, 'natural', 'volcano', 'app/images/josm/misc/landmark/volcano_small.png', 11, 7);
        OSM.Style.Utils.addArea(styleMap, 'natural', 'glacier', '#ffffff');
        OSM.Style.Utils.addPoint(styleMap, 'natural', 'glacier', 'app/images/josm/misc/landmark/glacier_small.png', 11, 8);
        OSM.Style.Utils.addArea(styleMap, 'natural', 'peak', '#663300');
        OSM.Style.Utils.addPoint(styleMap, 'natural', 'peak', 'app/images/josm/misc/landmark/peak_small.png', 11, 8);
        OSM.Style.Utils.addArea(styleMap, 'natural', 'spring', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'natural', 'spring', 'app/images/josm/misc/landmark/spring.png', 15, 9);

        OSM.Style.Utils.addArea(styleMap, 'military', 'range', '#b62c2c');
        OSM.Style.Utils.addPoint(styleMap, 'military', 'range', 'app/images/josm/misc/landmark/range.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'military', 'danger_area', '#b62c2c');
        OSM.Style.Utils.addPoint(styleMap, 'military', 'danger_area', 'app/images/josm/misc/danger.png', 16, 15);
        OSM.Style.Utils.addArea(styleMap, 'military', 'barracks', '#b62c2c');
        OSM.Style.Utils.addPoint(styleMap, 'military', 'barracks', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'military', 'bunker', '#b62c2c');
        OSM.Style.Utils.addPoint(styleMap, 'military', 'bunker', 'app/images/josm/misc/landmark/bunker.png', 16, 11);
        OSM.Style.Utils.addArea(styleMap, 'military', 'airfield', '#b62c2c');
        OSM.Style.Utils.addPoint(styleMap, 'military', 'airfield', 'app/images/josm/transport/airport/airfield.png', 11, 16);

        OSM.Style.Utils.addArea(styleMap, 'landuse', 'recreation_ground', '#b1e0c2');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'recreation_ground', 'app/images/josm/leisure/common.png', 13, 16);
        OSM.Style.Utils.addArea(styleMap, 'landuse', 'village_green', '#b1e0c2');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'village_green', 'app/images/josm/leisure/common.png', 13, 16);
        OSM.Style.Utils.addArea(styleMap, 'landuse', 'cemetery', '#b1efc8');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'cemetery', 'app/images/josm/rendering/landuse/cemetery.png', 11, 16);
        OSM.Style.Utils.addArea(styleMap, 'landuse', 'military', '#b62c2c');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'military', 'app/images/josm/vehicle/tank.png', 16, 10);
        OSM.Style.Utils.addStrokeArea(styleMap, 'landuse', 'construction', '#ffff00', '1');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'construction', 'app/images/josm/misc/construction.png', 16, 7);
        OSM.Style.Utils.addArea(styleMap, 'landuse', 'railway', '#888888');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'railway', 'app/images/josm/transport/railway_station.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'landuse', 'greenfield', '#b1ec5c');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'greenfield', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'landuse', 'brownfield', '#ecba32');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'brownfield', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'landuse', 'industrial', '#ecd8ff');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'industrial', 'app/images/josm/misc/landmark/works.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'landuse', 'commercial', '#dbdbdb');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'commercial', 'app/images/josm/misc/landuse/commercial.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'landuse', 'retail', '#dbdbdb');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'retail', 'app/images/josm/shop/mall.png', 12, 16);
        OSM.Style.Utils.addArea(styleMap, 'landuse', 'farmyard', '#f0f0f0');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'farmyard', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'landuse', 'residential', '#f0f0f0');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'residential', 'app/images/josm/misc/landuse/residential.png', 12, 16);
        OSM.Style.Utils.addArea(styleMap, 'landuse', 'grass', '#b1e0c2');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'grass', 'app/images/josm/misc/landmark/plant.png', 16, 14);
        OSM.Style.Utils.addArea(styleMap, 'landuse', 'allotments', '#b1e0c2');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'allotments', 'app/images/josm/misc/landmark/plant.png', 16, 14);
        OSM.Style.Utils.addArea(styleMap, 'landuse', 'forest', '#b1efc8');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'forest', 'app/images/josm/misc/landmark/trees.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'landuse', 'reservoir', '#0000bf');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'reservoir', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'landuse', 'basin', '#0000bf');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'basin', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'landuse', 'landfill', '#663300');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'landfill', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'landuse', 'quarry', '#888888');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'quarry', 'app/images/josm/misc/landmark/mine.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'landuse', 'orchard', '#b1e0c2');
        OSM.Style.Utils.addArea(styleMap, 'landuse', 'vineyard', '#b1e0c2');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'vineyard', 'app/images/josm/shop/groceries/fruits.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'landuse', 'meadow', '#b1e0c2');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'meadow', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'landuse', 'farmland', '#b1e0c2');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'farmland', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'landuse', 'farm', '#b1e0c2');
        OSM.Style.Utils.addPoint(styleMap, 'landuse', 'farm', 'app/images/josm/misc/landmark/farm.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'historic', 'boundary_stone', '#663300');
        OSM.Style.Utils.addPoint(styleMap, 'historic', 'boundary_stone', 'app/images/josm/historic/boundary_stone.png', 32, 32);
        OSM.Style.Utils.addArea(styleMap, 'historic', 'wayside_shrine', '#663300');
        OSM.Style.Utils.addPoint(styleMap, 'historic', 'wayside_shrine', 'app/images/josm/religion/wayside_shrine.png', 8, 16);
        OSM.Style.Utils.addArea(styleMap, 'historic', 'wayside_cross', '#663300');
        OSM.Style.Utils.addPoint(styleMap, 'historic', 'wayside_cross', 'app/images/josm/religion/wayside_cross.png', 16, 16);

        OSM.Style.Utils.addArea(styleMap, 'geological', 'palaeontological_site', '#663300');
        OSM.Style.Utils.addPoint(styleMap, 'geological', 'palaeontological_site', 'app/images/josm/historic/palaeontological_site.png', 16, 16);

        OSM.Style.Utils.addArea(styleMap, 'historic', 'battlefield', '#663300');
        OSM.Style.Utils.addPoint(styleMap, 'historic', 'battlefield', 'app/images/josm/sightseeing/battlefield.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'historic', 'ruins', '#663300');
        OSM.Style.Utils.addPoint(styleMap, 'historic', 'ruins', 'app/images/josm/sightseeing/ruins.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'historic', 'archaeological_site', '#663300');
        OSM.Style.Utils.addPoint(styleMap, 'historic', 'archaeological_site', 'app/images/josm/sightseeing/archaeological.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'historic', 'memorial', '#663300');
        OSM.Style.Utils.addPoint(styleMap, 'historic', 'memorial', 'app/images/josm/sightseeing/memorial.png', 7, 16);
        OSM.Style.Utils.addArea(styleMap, 'historic', 'monument', '#663300');
        OSM.Style.Utils.addPoint(styleMap, 'historic', 'monument', 'app/images/josm/sightseeing/monument.png', 10, 16);
        OSM.Style.Utils.addArea(styleMap, 'historic', 'castle', '#663300');
        OSM.Style.Utils.addPoint(styleMap, 'historic', 'castle', 'app/images/josm/sightseeing/castle.png', 12, 11);

        OSM.Style.Utils.addArea(styleMap, 'tourism', 'information', '#e180a2');
        OSM.Style.Utils.addPoint(styleMap, 'tourism', 'information', 'app/images/josm/misc/information.png', 16, 16);
        OSM.Style.Utils.addSubPoint(styleMap, 'tourism', 'information', 'information', 'board', 'app/images/josm/misc/information/board.png', 16, 16);
        OSM.Style.Utils.addSubPoint(styleMap, 'tourism', 'information', 'information', 'map', 'app/images/josm/misc/information/map.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'tourism', 'information', 'information', 'office', '#e180a2');
        OSM.Style.Utils.addSubPoint(styleMap, 'tourism', 'information', 'information', 'office', 'app/images/josm/misc/information/informationoffice.png', 16, 16);
        OSM.Style.Utils.addSubPoint(styleMap, 'tourism', 'information', 'information', 'guidepost', 'app/images/josm/misc/information/guidepost.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'tourism', 'museum', '#e180a2');
        OSM.Style.Utils.addPoint(styleMap, 'tourism', 'museum', 'app/images/josm/sightseeing/museum.png', 16, 16);
        OSM.Style.Utils.addStrokeArea(styleMap, 'tourism', 'artwork', '#e180a2', '2');
        OSM.Style.Utils.addPoint(styleMap, 'tourism', 'artwork', 'app/images/josm/service/arts_centre.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'tourism', 'zoo', '#e180a2');
        OSM.Style.Utils.addPoint(styleMap, 'tourism', 'zoo', 'app/images/josm/leisure/zoo.png', 16, 14);
        OSM.Style.Utils.addArea(styleMap, 'tourism', 'attraction', '#e180a2');
        OSM.Style.Utils.addPoint(styleMap, 'tourism', 'attraction', 'app/images/josm/sightseeing.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'tourism', 'theme_park', '#e180a2');
        OSM.Style.Utils.addPoint(styleMap, 'tourism', 'theme_park', 'app/images/josm/leisure/theme_park.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'tourism', 'viewpoint', '#e180a2');
        OSM.Style.Utils.addPoint(styleMap, 'tourism', 'viewpoint', 'app/images/josm/sightseeing/viewpoint.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'tourism', 'picnic_site', '#e180a2');
        OSM.Style.Utils.addPoint(styleMap, 'tourism', 'picnic_site', 'app/images/josm/leisure/picnic.png', 16, 15);
        OSM.Style.Utils.addArea(styleMap, 'tourism', 'caravan_site', '#e1a0a2');
        OSM.Style.Utils.addPoint(styleMap, 'tourism', 'caravan_site', 'app/images/josm/accommodation/camping/caravan.png', 16, 10);
        OSM.Style.Utils.addArea(styleMap, 'tourism', 'camp_site', '#e1a0a2');
        OSM.Style.Utils.addPoint(styleMap, 'tourism', 'camp_site', 'app/images/josm/accommodation/camping.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'tourism', 'alpine_hut', '#e1a0a2');
        OSM.Style.Utils.addPoint(styleMap, 'tourism', 'alpine_hut', 'app/images/josm/accommodation/alpine_hut.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'tourism', 'chalet', '#e1a0a2');
        OSM.Style.Utils.addPoint(styleMap, 'tourism', 'chalet', 'app/images/josm/accommodation/chalet.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'tourism', 'hostel', '#e1a0a2');
        OSM.Style.Utils.addPoint(styleMap, 'tourism', 'hostel', 'app/images/josm/accommodation/hostel.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'tourism', 'guest_house', '#e1a0a2');
        OSM.Style.Utils.addPoint(styleMap, 'tourism', 'guest_house', 'app/images/josm/accommodation/guest_house.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'tourism', 'motel', '#e1a0a2');
        OSM.Style.Utils.addPoint(styleMap, 'tourism', 'motel', 'app/images/josm/accommodation/motel.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'tourism', 'hotel', '#e1a0a2');
        OSM.Style.Utils.addPoint(styleMap, 'tourism', 'hotel', 'app/images/josm/accommodation.png', 16, 16);

        OSM.Style.Utils.addArea(styleMap, 'shop', 'shopping_centre', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'shopping_centre', 'app/images/josm/shop/mall.png', 12, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'video', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'video', 'app/images/josm/shop/video.png', 16, 6);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'toys', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'toys', 'app/images/josm/shop/toys.png', 15, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'travel_agency', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'travel_agency', 'app/images/josm/place/island.png', 16, 14);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'tailor', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'tailor', 'app/images/josm/shop/tailor.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'stationery', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'stationery', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'sports', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'sports', 'app/images/josm/sport/multi.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'shoes', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'shoes', 'app/images/josm/shop/shoes.png', 16, 9);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'optician', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'optician', 'app/images/josm/shop/optician.png', 16, 7);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'organic', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'organic', 'app/images/josm/shop/groceries/fruits.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'newsagent', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'newsagent', 'app/images/josm/shop/kiosk.png', 11, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'motorcycle', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'motorcycle', 'app/images/josm/vehicle/motorbike.png', 16, 12);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'mall', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'mall', 'app/images/josm/shop/mall.png', 12, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'jewelry', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'jewelry', 'app/images/josm/shop/jewelry.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'hifi', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'hifi', 'app/images/josm/shop/hifi.png', 14, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'hardware', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'hardware', 'app/images/josm/shop/diy_store.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'hairdresser', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'hairdresser', 'app/images/josm/shop/hairdresser.png', 12, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'garden_centre', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'garden_centre', 'app/images/josm/shop/garden_centre.png', 14, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'groceries', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'groceries', 'app/images/josm/shop/groceries/fruits.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'florist', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'florist', 'app/images/josm/shop/florist.png', 12, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'furniture', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'furniture', 'app/images/josm/shop/furniture.png', 14, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'electronics', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'electronics', 'app/images/josm/shop/electronics.png', 16, 13);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'department_store', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'department_store', 'app/images/josm/shop/mall.png', 12, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'cycle_repair', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'cycle_repair', 'app/images/josm/sport/bicycle.png', 16, 10);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'computer', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'computer', 'app/images/josm/shop/computer.png', 16, 13);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'clothes', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'clothes', 'app/images/josm/shop/clothes.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'chemist', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'chemist', 'app/images/josm/shop/chemist.png', 16, 8);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'car_repair', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'car_repair', 'app/images/josm/transport/car.png', 16, 9);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'car_dealer', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'car_dealer', 'app/images/josm/transport/car.png', 16, 9);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'car', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'car', 'app/images/josm/transport/car.png', 16, 9);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'books', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'books', 'app/images/josm/shop/rental/library.png', 8, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'beverages', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'beverages', 'app/images/josm/shop/beverages.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'alcohol', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'alcohol', 'app/images/josm/shop/beverages.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'kiosk', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'kiosk', 'app/images/josm/shop/kiosk.png', 11, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'outdoor', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'outdoor', 'app/images/josm/shop/sports/outdoor.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'laundry', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'laundry', 'app/images/josm/shop/laundry.png', 11, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'dry_cleaning', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'dry_cleaning', 'app/images/josm/shop/laundry.png', 11, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'doityourself', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'doityourself', 'app/images/josm/shop/diy_store.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'bicycle', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'bicycle', 'app/images/josm/sport/bicycle.png', 16, 10);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'butcher', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'butcher', 'app/images/josm/shop/groceries/butcher.png', 16, 10);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'bakery', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'bakery', 'app/images/josm/shop/groceries/bakery.png', 14, 11);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'convenience', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'convenience', 'app/images/josm/shop/supermarket.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'shop', 'supermarket', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'shop', 'supermarket', 'app/images/josm/shop/supermarket.png', 16, 16);

        OSM.Style.Utils.addArea(styleMap, 'amenity', 'vending_machine', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'vending_machine', 'app/images/josm/transport/ticket-machine.png', 16, 16);
        OSM.Style.Utils.addSubPoint(styleMap, 'amenity', 'vending_machine', 'vending', 'excrement_bags', 'app/images/josm/service/excrement_bags.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'wlan', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'wlan', 'app/images/josm/wlan.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'marketplace', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'marketplace', 'app/images/josm/place/marketplace.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'hunting_stand', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'hunting_stand', 'app/images/josm/hunting_stand.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'shelter', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'shelter', 'app/images/josm/accommodation/shelter.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'fire_hydrant', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'fire_hydrant', 'app/images/josm/service/fire_hydrant.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'bbq', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'bbq', 'app/images/josm/leisure/bbq.png', 10, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'bench', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'bench', 'app/images/josm/leisure/bench.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'atm', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'atm', 'app/images/josm/money/atm.png', 11, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'bureau_de_change', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'bureau_de_change', 'app/images/josm/money/exchange.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'bank', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'bank', 'app/images/josm/money/bank.png', 14, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'prison', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'prison', 'app/images/josm/service/administration/prison.png', 12, 14);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'courthouse', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'courthouse', 'app/images/josm/service/administration/court_of_law.png', 16, 11);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'arts_centre', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'arts_centre', 'app/images/josm/service/arts_centre.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'cinema', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'cinema', 'app/images/josm/leisure/cinema.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'theatre', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'theatre', 'app/images/josm/leisure/theater.png', 16, 15);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'ferry_terminal', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'ferry_terminal', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'bus_station', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'bus_station', 'app/images/josm/transport/bus.png', 13, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'fire_station', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'fire_station', 'app/images/josm/service/firebrigade.png', 16, 8);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'police', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'police', 'app/images/josm/service/police.png', 14, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'library', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'library', 'app/images/josm/shop/rental/library.png', 8, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'veterinary', '#eeeeee');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'veterinary', 'app/images/josm/health/veterinary.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'dentist', '#eeeeee');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'dentist', 'app/images/josm/health/dentist.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'doctors', '#eeeeee');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'doctors', 'app/images/josm/health/doctor.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'baby_hatch', '#eeeeee');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'baby_hatch', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'nursery', '#eeeeee');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'nursery', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'hospital', '#eeeeee');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'hospital', 'app/images/josm/health/hospital.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'pharmacy', '#eeeeee');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'pharmacy', 'app/images/josm/health/pharmacy.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'driving_school', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'driving_school', 'app/images/josm/education/driving_school.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'kindergarten', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'kindergarten', 'app/images/josm/education/kindergarten.png', 16, 14);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'college', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'college', 'app/images/josm/education/college.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'university', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'university', 'app/images/josm/education/university.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'school', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'school', 'app/images/josm/education/school.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'post_box', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'post_box', 'app/images/josm/service/post_box.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'post_office', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'post_office', 'app/images/josm/service/post_office.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'crematorium', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'crematorium', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'grave_yard', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'grave_yard', 'app/images/josm/rendering/landuse/cemetery.png', 11, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'place_of_worship', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'place_of_worship', 'app/images/josm/religion.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'fountain', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'fountain', 'app/images/josm/misc/landmark/spring.png', 15, 9);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'drinking_water', '#00005f');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'drinking_water', 'app/images/josm/food/drinking_water.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'community_centre', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'community_centre', 'app/images/josm/service.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'townhall', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'townhall', 'app/images/josm/service.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'embassy', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'embassy', 'app/images/josm/service.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'public_building', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'public_building', 'app/images/josm/service.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'waste_basket', 'app/images/josm/service/recycling/trash-bin.png', 15, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'recycling', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'recycling', 'app/images/josm/service/recycling.png', 16, 15);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'toilets', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'toilets', 'app/images/josm/service/toilets.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'emergency_phone', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'emergency_phone', 'app/images/josm/vehicle/emergency_phone.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'clock', 'app/images/josm/service/clock.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'telephone', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'telephone', 'app/images/josm/service/telephone.png', 16, 20);
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'grit_bin', 'app/images/josm/misc/grit_bin.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'fuel', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'fuel', 'app/images/josm/vehicle/fuel.png', 14, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'taxi', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'taxi', 'app/images/josm/transport/taxi.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'car_wash', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'car_wash', 'app/images/josm/vehicle/car_wash.png', 16, 12);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'car_sharing', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'car_sharing', 'app/images/josm/vehicle/car_sharing.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'car_rental', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'car_rental', 'app/images/josm/vehicle/rental/car.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'bicycle_rental', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'bicycle_rental', 'app/images/josm/vehicle/rental/bicycle.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'bicycle_parking', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'bicycle_parking', 'app/images/josm/vehicle/parking/bicycle.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'parking', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'parking', 'app/images/josm/vehicle/parking.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'parking', 'surface', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'parking', 'surface', 'app/images/josm/vehicle/parking.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'parking', 'park_and_ride', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'parking', 'park_and_ride', 'app/images/josm/vehicle/parking/park_ride.png', 16, 14);
        OSM.Style.Utils.addArea(styleMap, 'parking', 'underground', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'parking', 'underground', 'app/images/josm/vehicle/parking/underground.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'parking', 'multi-storey', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'parking', 'multi-storey', 'app/images/josm/vehicle/parking/multi-storey.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'ice_cream', '#ecba52');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'ice_cream', 'app/images/josm/food/icecream.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'bar', '#ecba52');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'bar', 'app/images/josm/food/bar.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'fast_food', '#ecba52');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'fast_food', 'app/images/josm/food/fastfood.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'food_court', '#ecba52');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'food_court', 'app/images/josm/food/restaurant.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'restaurant', '#ecba52');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'restaurant', 'app/images/josm/food/restaurant.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'cafe', '#ecba52');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'cafe', 'app/images/josm/food/cafe.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'brothel', '#ecba52');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'brothel', 'app/images/josm/leisure/stripclub.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'stripclub', '#ecba52');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'stripclub', 'app/images/josm/leisure/stripclub.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'nightclub', '#ecba52');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'nightclub', 'app/images/josm/leisure/nightclub.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'biergarten', '#ecba52');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'biergarten', 'app/images/josm/food/biergarten.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'amenity', 'pub', '#ecba52');
        OSM.Style.Utils.addPoint(styleMap, 'amenity', 'pub', 'app/images/josm/food/pub.png', 16, 16);

        OSM.Style.Utils.addArea(styleMap, 'leisure', 'ice_rink', '#c7f1a3');
        OSM.Style.Utils.addPoint(styleMap, 'leisure', 'ice_rink', 'app/images/josm/sport/hockey.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'leisure', 'dog_park', '#c7f1a3');
        OSM.Style.Utils.addPoint(styleMap, 'leisure', 'dog_park', 'app/images/josm/leisure/dog.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'leisure', 'miniature_golf', '#c7f1a3');
        OSM.Style.Utils.addPoint(styleMap, 'leisure', 'miniature_golf', 'app/images/josm/sport/golf.png', 9, 16);
        OSM.Style.Utils.addArea(styleMap, 'leisure', 'swimming_pool', '#c7f1a3');
        OSM.Style.Utils.addPoint(styleMap, 'leisure', 'swimming_pool', 'app/images/josm/sport/pool.png', 16, 11);
        OSM.Style.Utils.addArea(styleMap, 'leisure', 'common', '#c7f1a3');
        OSM.Style.Utils.addPoint(styleMap, 'leisure', 'common', 'app/images/josm/leisure/common.png', 13, 16);
        OSM.Style.Utils.addArea(styleMap, 'leisure', 'garden', '#c7f1a3');
        OSM.Style.Utils.addPoint(styleMap, 'leisure', 'garden', 'app/images/josm/leisure/garden.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'leisure', 'playground', '#c7f1a3');
        OSM.Style.Utils.addPoint(styleMap, 'leisure', 'playground', 'app/images/josm/leisure/playground.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'leisure', 'park', '#c7f1a3');
        OSM.Style.Utils.addPoint(styleMap, 'leisure', 'park', 'app/images/josm/leisure/park.png', 8, 8);
        OSM.Style.Utils.addArea(styleMap, 'leisure', 'nature_reserve', '#c7f1a3');
        OSM.Style.Utils.addPoint(styleMap, 'leisure', 'nature_reserve', 'app/images/josm/leisure/nature_reserve.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'leisure', 'fishing', '#c7f1a3');
        OSM.Style.Utils.addPoint(styleMap, 'leisure', 'fishing', 'app/images/josm/sport/fishing.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'leisure', 'slipway', '#c7f1a3');
        OSM.Style.Utils.addPoint(styleMap, 'leisure', 'slipway', 'app/images/josm/nautical/slipway.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'leisure', 'marina', '#0070cf');
        OSM.Style.Utils.addPoint(styleMap, 'leisure', 'marina', 'app/images/josm/nautical/marina.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'leisure', 'water_park', '#c7f1a3');
        OSM.Style.Utils.addPoint(styleMap, 'leisure', 'water_park', 'app/images/josm/leisure/water_park.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'leisure', 'pitch', '#c7f1a3');
        OSM.Style.Utils.addPoint(styleMap, 'leisure', 'pitch', 'app/images/josm/sport/pitch.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'leisure', 'track', '#c7f1a3');
        OSM.Style.Utils.addPoint(styleMap, 'leisure', 'track', 'app/images/josm/sport/track.png', 15, 15);
        OSM.Style.Utils.addArea(styleMap, 'leisure', 'stadium', '#c7f1a3');
        OSM.Style.Utils.addPoint(styleMap, 'leisure', 'stadium', 'app/images/josm/sport/stadium.png', 16, 10);
        OSM.Style.Utils.addArea(styleMap, 'leisure', 'golf_course', '#c7f1a3');
        OSM.Style.Utils.addPoint(styleMap, 'leisure', 'golf_course', 'app/images/josm/sport/golf.png', 9, 16);
        OSM.Style.Utils.addArea(styleMap, 'leisure', 'sports_centre', '#c7f1a3');
        OSM.Style.Utils.addPoint(styleMap, 'leisure', 'sports_centre', 'app/images/josm/sport/centre.png', 16, 16);

        OSM.Style.Utils.addArea(styleMap, 'man_made', 'water_works', '#d8d8d8');
        OSM.Style.Utils.addPoint(styleMap, 'man_made', 'water_works', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'man_made', 'works', '#d8d8d8');
        OSM.Style.Utils.addPoint(styleMap, 'man_made', 'works', 'app/images/josm/misc/landmark/works.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'man_made', 'windmill', '#d8d8d8');
        OSM.Style.Utils.addPoint(styleMap, 'man_made', 'windmill', 'app/images/josm/misc/landmark/windmill.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'man_made', 'water_tower', '#d8d8d8');
        OSM.Style.Utils.addPoint(styleMap, 'man_made', 'water_tower', 'app/images/josm/misc/landmark/water_tower.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'man_made', 'watermill', '#d8d8d8');
        OSM.Style.Utils.addPoint(styleMap, 'man_made', 'watermill', 'app/images/josm/misc/landmark/watermill.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'man_made', 'wastewater_plant', '#d8d8d8');
        OSM.Style.Utils.addPoint(styleMap, 'man_made', 'wastewater_plant', 'app/images/josm/misc/landmark/wastewater_plant.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'man_made', 'tower', '#d8d8d8');
        OSM.Style.Utils.addPoint(styleMap, 'man_made', 'tower', 'app/images/josm/misc/landmark/tower.png', 10, 16);
        OSM.Style.Utils.addArea(styleMap, 'man_made', 'survey_point', '#d8d8d8');
        OSM.Style.Utils.addPoint(styleMap, 'man_made', 'survey_point', 'app/images/josm/misc/landmark/survey_point.png', 9, 16);
        OSM.Style.Utils.addArea(styleMap, 'man_made', 'surveillance', '#d8d8d8');
        OSM.Style.Utils.addPoint(styleMap, 'man_made', 'surveillance', 'app/images/josm/misc/surveillance.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'man_made', 'reservoir_covered', '#d8d8d8');
        OSM.Style.Utils.addPoint(styleMap, 'man_made', 'reservoir_covered', 'app/images/josm/misc/landmark/reservoir_covered.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'man_made', 'petroleum_well', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addStroke(styleMap, 'man_made', 'pipeline', '#660000', 4);
        OSM.Style.Utils.addStrokeArea(styleMap, 'man_made', 'pier', '#660000', '2');
        OSM.Style.Utils.addPoint(styleMap, 'man_made', 'pier', 'app/images/josm/nautical/pier.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'man_made', 'lighthouse', '#d8d8d8');
        OSM.Style.Utils.addPoint(styleMap, 'man_made', 'lighthouse', 'app/images/josm/misc/landmark/lighthouse.png', 13, 16);
        OSM.Style.Utils.addArea(styleMap, 'man_made', 'gasometer', '#d8d8d8');
        OSM.Style.Utils.addPoint(styleMap, 'man_made', 'gasometer', 'app/images/josm/misc/landmark/gasometer.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'man_made', 'flagpole', '#d8d8d8');
        OSM.Style.Utils.addPoint(styleMap, 'man_made', 'flagpole', 'app/images/josm/misc/flag.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'man_made', 'crane', '#d8d8d8');
        OSM.Style.Utils.addPoint(styleMap, 'man_made', 'crane', 'app/images/josm/misc/landmark/crane.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'man_made', 'beacon', '#d8d8d8');
        OSM.Style.Utils.addPoint(styleMap, 'man_made', 'beacon', 'app/images/josm/misc/landmark/beacon.png', 11, 16);
        OSM.Style.Utils.addArea(styleMap, 'power', 'generator', '#eeeeee');
        OSM.Style.Utils.addPoint(styleMap, 'power', 'generator', 'app/images/josm/misc/landmark/power.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'power', 'generator', 'power_source', 'nuclear', '#eeeeee');
        OSM.Style.Utils.addSubPoint(styleMap, 'power', 'generator', 'power_source', 'nuclear', 'app/images/josm/misc/landmark/power/nuclear.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'power', 'generator', 'power_source', 'photovoltaic', '#eeeeee');
        OSM.Style.Utils.addSubPoint(styleMap, 'power', 'generator', 'power_source', 'photovoltaic', 'app/images/josm/misc/landmark/power/fossil.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'power', 'generator', 'power_source', 'gas', '#eeeeee');
        OSM.Style.Utils.addSubPoint(styleMap, 'power', 'generator', 'power_source', 'gas', 'app/images/josm/misc/landmark/power/fossil.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'power', 'generator', 'power_source', 'coal', '#eeeeee');
        OSM.Style.Utils.addSubPoint(styleMap, 'power', 'generator', 'power_source', 'coal', 'app/images/josm/misc/landmark/power/fossil.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'power', 'generator', 'power_source', 'fossil', '#eeeeee');
        OSM.Style.Utils.addSubPoint(styleMap, 'power', 'generator', 'power_source', 'fossil', 'app/images/josm/misc/landmark/power/fossil.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'power', 'generator', 'power_source', 'hydro', '#eeeeee');
        OSM.Style.Utils.addSubPoint(styleMap, 'power', 'generator', 'power_source', 'hydro', 'app/images/josm/misc/landmark/power/hydro.png', 16, 16);
        OSM.Style.Utils.addSubArea(styleMap, 'power', 'generator', 'power_source', 'wind', '#eeeeee');
        OSM.Style.Utils.addSubPoint(styleMap, 'power', 'generator', 'power_source', 'wind', 'app/images/josm/misc/landmark/power/wind.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'power', 'sub_station', '#eeeeee');
        OSM.Style.Utils.addPoint(styleMap, 'power', 'sub_station', 'app/images/josm/misc/landmark/power.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'power', 'station', '#eeeeee');
        OSM.Style.Utils.addPoint(styleMap, 'power', 'station', 'app/images/josm/misc/landmark/power.png', 16, 16);
        OSM.Style.Utils.addStroke(styleMap, 'power', 'minor_line', '#eeeeee', 3);
        OSM.Style.Utils.addStroke(styleMap, 'power', 'line', '#eeeeee', 3);
        OSM.Style.Utils.addPoint(styleMap, 'power', 'pole', 'app/images/josm/misc/landmark/power/pole.png', 9, 16);
        OSM.Style.Utils.addArea(styleMap, 'power', 'tower', '#eeeeee');
        OSM.Style.Utils.addPoint(styleMap, 'power', 'tower', 'app/images/josm/misc/landmark/power/tower_small.png', 7, 16);

        OSM.Style.Utils.addSubStrokeArea(styleMap, 'route', 'piste', 'piste:difficulty', 'novice', '#00ff00', '6');
        OSM.Style.Utils.addSubPoint(styleMap, 'route', 'piste', 'piste:difficulty', 'novice', 'app/images/josm/sport/skiing.png', 15, 16);
        OSM.Style.Utils.addSubStrokeArea(styleMap, 'route', 'piste', 'piste:difficulty', 'freeride', '#ffff00', '6');
        OSM.Style.Utils.addSubPoint(styleMap, 'route', 'piste', 'piste:difficulty', 'freeride', 'app/images/josm/sport/skiing.png', 15, 16);
        OSM.Style.Utils.addSubStrokeArea(styleMap, 'route', 'piste', 'piste:difficulty', 'expert', '#606060', '6');
        OSM.Style.Utils.addSubPoint(styleMap, 'route', 'piste', 'piste:difficulty', 'expert', 'app/images/josm/sport/skiing.png', 15, 16);
        OSM.Style.Utils.addSubStrokeArea(styleMap, 'route', 'piste', 'piste:difficulty', 'advanced', '#606060', '6');
        OSM.Style.Utils.addSubPoint(styleMap, 'route', 'piste', 'piste:difficulty', 'advanced', 'app/images/josm/sport/skiing.png', 15, 16);
        OSM.Style.Utils.addSubStrokeArea(styleMap, 'route', 'piste', 'piste:difficulty', 'intermediate', '#ff0000', '6');
        OSM.Style.Utils.addSubPoint(styleMap, 'route', 'piste', 'piste:difficulty', 'intermediate', 'app/images/josm/sport/skiing.png', 15, 16);
        OSM.Style.Utils.addSubStrokeArea(styleMap, 'route', 'piste', 'piste:difficulty', 'easy', '#0000ff', '6');
        OSM.Style.Utils.addSubPoint(styleMap, 'route', 'piste', 'piste:difficulty', 'easy', 'app/images/josm/sport/skiing.png', 15, 16);

        OSM.Style.Utils.addArea(styleMap, 'aerialway', 'pylon', '#663300');
        OSM.Style.Utils.addPoint(styleMap, 'aerialway', 'pylon', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'aerialway', 'station', '#663300');
        OSM.Style.Utils.addPoint(styleMap, 'aerialway', 'station', 'app/images/josm/transport/aerialway/station.png', 16, 12);
        OSM.Style.Utils.addStroke(styleMap, 'aerialway', 'drag_lift', '#663300', 4, 'dash');
        OSM.Style.Utils.addPoint(styleMap, 'aerialway', 'drag_lift', 'app/images/josm/transport/aerialway/drag_lift.png', 14, 16);
        OSM.Style.Utils.addStroke(styleMap, 'aerialway', 'chair_lift', '#663300', 4, 'dash');
        OSM.Style.Utils.addPoint(styleMap, 'aerialway', 'chair_lift', 'app/images/josm/transport/aerialway/chair_lift.png', 16, 16);
        OSM.Style.Utils.addStroke(styleMap, 'aerialway', 'gondola', '#663300', 4, 'dash');
        OSM.Style.Utils.addPoint(styleMap, 'aerialway', 'gondola', 'app/images/josm/transport/aerialway/cable_car.png', 15, 16);
        OSM.Style.Utils.addStroke(styleMap, 'aerialway', 'cable_car', '#663300', 4, 'dash');
        OSM.Style.Utils.addPoint(styleMap, 'aerialway', 'cable_car', 'app/images/josm/transport/aerialway/cable_car.png', 15, 16);

        OSM.Style.Utils.addPoint(styleMap, 'aeroway', 'windsock', 'app/images/josm/transport/airport/windsock.png', 12, 14);
        OSM.Style.Utils.addPoint(styleMap, 'aeroway', 'gate', 'app/images/josm/transport/airport/terminal.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'aeroway', 'apron', '#990000');
        OSM.Style.Utils.addPoint(styleMap, 'aeroway', 'apron', 'app/images/josm/transport/airport.png', 16, 16);
        OSM.Style.Utils.addStroke(styleMap, 'aeroway', 'taxiway', '#660000', 5);
        OSM.Style.Utils.addPoint(styleMap, 'aeroway', 'taxiway', 'app/images/josm/transport/airport.png', 16, 16);
        OSM.Style.Utils.addStroke(styleMap, 'aeroway', 'runway', '#330000', 6);
        OSM.Style.Utils.addPoint(styleMap, 'aeroway', 'runway', 'app/images/josm/transport/airport.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'aeroway', 'helipad', '#330000');
        OSM.Style.Utils.addPoint(styleMap, 'aeroway', 'helipad', 'app/images/josm/transport/airport/helipad.png', 16, 11);
        OSM.Style.Utils.addArea(styleMap, 'aeroway', 'terminal', '#bb0000');
        OSM.Style.Utils.addPoint(styleMap, 'aeroway', 'terminal', 'app/images/josm/transport/airport/terminal.png', 16, 16);
        OSM.Style.Utils.addStrokeArea(styleMap, 'aeroway', 'aerodrome', '#660000', '2');
        OSM.Style.Utils.addPoint(styleMap, 'aeroway', 'aerodrome', 'app/images/josm/transport/airport.png', 16, 16);

        OSM.Style.Utils.addStroke(styleMap, 'railway', 'funicular', '#404040', 3, 'dash');
        OSM.Style.Utils.addStrokeArea(styleMap, 'railway', 'platform', '#404040', '2');
        OSM.Style.Utils.addArea(styleMap, 'railway', 'buffer_stop', '#404040');
        OSM.Style.Utils.addPoint(styleMap, 'railway', 'buffer_stop', 'app/images/josm/transport/buffer_stop.png', 16, 9);
        OSM.Style.Utils.addArea(styleMap, 'railway', 'turntable', '#404040');
        OSM.Style.Utils.addPoint(styleMap, 'railway', 'turntable', 'app/images/josm/transport/turntable.png', 16, 15);
        OSM.Style.Utils.addStroke(styleMap, 'railway', 'monorail', '#404040', 3, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'railway', 'narrow_gauge', '#404040', 3, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'railway', 'abandoned', '#404040', 3, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'railway', 'disused', '#404040', 3, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'railway', 'preserved', '#404040', 3, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'railway', 'subway', '#606060', 3, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'railway', 'light_rail', '#808080', 5, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'railway', 'tram', '#808080', 3, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'railway', 'rail', '#404040', 5, 'dash');
        OSM.Style.Utils.addArea(styleMap, 'railway', 'level_crossing', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'railway', 'level_crossing', 'app/images/josm/vehicle/crossing.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'railway', 'crossing', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'railway', 'crossing', 'app/images/josm/vehicle/crossing_small.png', 10, 10);
        OSM.Style.Utils.addArea(styleMap, 'railway', 'subway_entrance', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'railway', 'subway_entrance', 'app/images/josm/transport/underground.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'railway', 'tram_stop', 'app/images/josm/transport/railway_small.png', 5, 5);
        OSM.Style.Utils.addArea(styleMap, 'railway', 'tram_station', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'railway', 'tram_station', 'app/images/josm/transport/railway_station.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'railway', 'halt', 'app/images/josm/transport/railway_small.png', 5, 5);
        OSM.Style.Utils.addArea(styleMap, 'railway', 'station', '#f7efb7');
        OSM.Style.Utils.addPoint(styleMap, 'railway', 'station', 'app/images/josm/transport/railway_station.png', 16, 16);

        OSM.Style.Utils.addStroke(styleMap, 'waterway', 'waterfall', '#d8d8d8', 5);
        OSM.Style.Utils.addPoint(styleMap, 'waterway', 'waterfall', 'app/images/josm/nautical/waterfall.png', 16, 16);
        OSM.Style.Utils.addStrokeArea(styleMap, 'waterway', 'dam', '#d8d8d8', '2');
        OSM.Style.Utils.addPoint(styleMap, 'waterway', 'dam', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addStroke(styleMap, 'waterway', 'rapids', '#8080ff', 5);
        OSM.Style.Utils.addPoint(styleMap, 'waterway', 'rapids', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addStroke(styleMap, 'waterway', 'weir', '#d8d8d8', 5);
        OSM.Style.Utils.addPoint(styleMap, 'waterway', 'weir', 'app/images/josm/nautical/weir.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'waterway', 'mooring', 'app/images/josm/nautical/marina.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'waterway', 'waste_disposal', 'app/images/josm/accommodation/camping/wastewater.png', 16, 11);
        OSM.Style.Utils.addPoint(styleMap, 'waterway', 'water_point', 'app/images/josm/accommodation/camping/water.png', 12, 16);
        OSM.Style.Utils.addArea(styleMap, 'waterway', 'boatyard', '#d8d8d8');
        OSM.Style.Utils.addPoint(styleMap, 'waterway', 'boatyard', 'app/images/josm/nautical/boatyard.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'waterway', 'turning_point', 'app/images/josm/nautical/turning.png', 16, 11);
        OSM.Style.Utils.addPoint(styleMap, 'waterway', 'lock_gate', 'app/images/josm/nautical/lock_gate.png', 16, 10);
        OSM.Style.Utils.addArea(styleMap, 'waterway', 'dock', '#0000cf');
        OSM.Style.Utils.addPoint(styleMap, 'waterway', 'dock', 'app/images/josm/nautical/boatyard.png', 16, 16);
        OSM.Style.Utils.addStroke(styleMap, 'waterway', 'drain', '#0000ff', 3);
        OSM.Style.Utils.addStroke(styleMap, 'waterway', 'ditch', '#0000ff', 3);
        OSM.Style.Utils.addStroke(styleMap, 'waterway', 'stream', '#6600cc', 3);
        OSM.Style.Utils.addStroke(styleMap, 'waterway', 'canal', '#0000ff', 5);
        OSM.Style.Utils.addStrokeArea(styleMap, 'waterway', 'riverbank', '#0000cf', '1');
        OSM.Style.Utils.addStroke(styleMap, 'waterway', 'river', '#0000ff', 5);
        // TODO
        OSM.Style.Utils.addSubStroke(styleMap, 'highway', 'track', 'tracktype', 'grade5', '#006600', 3, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'highway', 'track', 'tracktype', 'grade4', '#006600', 3, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'highway', 'track', 'tracktype', 'grade3', '#006600', 3, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'highway', 'track', 'tracktype', 'grade2', '#006600', 3, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'highway', 'track', 'tracktype', 'grade1', '#006600', 3, 'dash');
        OSM.Style.Utils.addSubArea(styleMap, 'highway', '*', 'junction', 'roundabout', '#eeeeee');
        OSM.Style.Utils.addArea(styleMap, 'highway', 'emergency_access_point', '#c0c0c0');
        OSM.Style.Utils.addPoint(styleMap, 'highway', 'emergency_access_point', 'app/images/josm/service/emergency_access_point.png', 16, 16);
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'construction', '#ffff00', 5, 'dash');
        OSM.Style.Utils.addPoint(styleMap, 'highway', 'construction', 'app/images/josm/misc/construction.png', 16, 7);
        OSM.Style.Utils.addPoint(styleMap, 'highway', 'passing_place', 'app/images/josm/vehicle/passing_place.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'highway', 'turning_circle', '#c0c0c0');
        OSM.Style.Utils.addPoint(styleMap, 'highway', 'turning_circle', 'app/images/josm/vehicle/turning_circle.png', 16, 7);
        OSM.Style.Utils.addPoint(styleMap, 'highway', 'bus_stop', 'app/images/josm/transport/bus_small.png', 10, 10);
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'ford', '#ff0000', 5);
        OSM.Style.Utils.addPoint(styleMap, 'highway', 'ford', 'app/images/josm/vehicle/ford.png', 16, 11);
        OSM.Style.Utils.addArea(styleMap, 'highway', 'services', '#c0c0c0');
        OSM.Style.Utils.addPoint(styleMap, 'highway', 'services', 'app/images/josm/vehicle/services.png', 16, 14);
        OSM.Style.Utils.addPoint(styleMap, 'highway', 'motorway_junction', 'app/images/josm/vehicle/exit.png', 16, 13);
        OSM.Style.Utils.addPoint(styleMap, 'highway', 'incline_steep', 'app/images/josm/vehicle/restriction/incline.png', 16, 14);
        OSM.Style.Utils.addPoint(styleMap, 'highway', 'incline', 'app/images/josm/vehicle/restriction/incline.png', 16, 14);
        OSM.Style.Utils.addPoint(styleMap, 'highway', 'crossing', 'app/images/josm/vehicle/zebra_crossing.png', 14, 7);
        OSM.Style.Utils.addPoint(styleMap, 'traffic_sign', 'city_limit', 'app/images/josm/vehicle/restriction/citylimit.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'highway', 'speed_camera', 'app/images/josm/vehicle/restriction/speed_trap.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'highway', 'street_lamp', 'app/images/josm/misc/streetlamp.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'highway', 'traffic_signals', 'app/images/josm/vehicle/restriction/traffic-light.png', 6, 16);
        OSM.Style.Utils.addPoint(styleMap, 'highway', 'stop', 'app/images/josm/vehicle/restriction/stop.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'highway', 'mini_roundabout', 'app/images/josm/vehicle/restriction/roundabout_right.png', 16, 16);
        OSM.Style.Utils.addSubPoint(styleMap, 'highway', 'mini_roundabout', 'direction', 'clockwise', 'app/images/josm/vehicle/restriction/roundabout_left.png', 16, 16);
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'bus_guideway', '#404040', 3, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'steps', '#00ff00', 3, 'dash');
        OSM.Style.Utils.addPoint(styleMap, 'highway', 'steps', 'app/images/josm/transport/steps.png', 16, 16);
        OSM.Style.Utils.addStrokeArea(styleMap, 'highway', 'pedestrian', '#00ff00', '3');
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'path', '#b100ff', 3, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'path', '#b100ff', 3, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'path', '#00ff00', 3);
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'path', '#00ff00', 3);
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'path', '#b100ff', 3);
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'path', '#b100ff', 3);
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'path', '#00ff00', 3, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'footway', '#00ff00', 3);
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'cycleway', '#b100ff', 3);
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'bridleway', '#c08000', 3);
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'service', '#809bc0', 3);
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'living_street', '#c0c0c0', 5, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'residential', '#c0c0c0', 5);
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'track', '#006600', 3);
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'unsurfaced', '#c0c0c0', 3);
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'road', '#ff0000', 5, 'dash');
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'unclassified', '#c0c0c0', 5);
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'tertiary', '#f7f496', 5);
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'secondary_link', '#fdbf6f', 7);
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'secondary', '#fdbf6f', 7);
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'primary_link', '#fb805f', 7);
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'primary', '#fb805f', 7);
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'trunk_link', '#7fc97f', 7);
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'trunk', '#7fc97f', 7);
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'motorway_link', '#809bc0', 7);
        OSM.Style.Utils.addStroke(styleMap, 'highway', 'motorway', '#809bc0', 7);

        OSM.Style.Utils.addPoint(styleMap, 'barrier', 'hampshire_gate', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'barrier', 'drawbridge', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'barrier', 'bus_trap', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'barrier', 'spikes', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'barrier', 'portcullis', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'barrier', 'sally_port', 'app/images/josm/vehicle/sally_port.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'barrier', 'bump_gate', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'barrier', 'border_control', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addStrokeArea(styleMap, 'barrier', 'block', '#F0F050', '3');
        OSM.Style.Utils.addPoint(styleMap, 'barrier', 'block', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'barrier', 'cattle_grid', 'app/images/josm/vehicle/cattle_grid.png', 16, 6);
        OSM.Style.Utils.addStrokeArea(styleMap, 'barrier', 'retaining_wall', '#F0F050', '3');
        OSM.Style.Utils.addPoint(styleMap, 'barrier', 'entrance', 'app/images/josm/vehicle/entrance.png', 16, 16);
        OSM.Style.Utils.addStrokeArea(styleMap, 'barrier', 'city_wall', '#F0F050', '3');
        OSM.Style.Utils.addPoint(styleMap, 'barrier', 'kissing_gate', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addArea(styleMap, 'barrier', 'toll_booth', '#F0F050');
        OSM.Style.Utils.addPoint(styleMap, 'barrier', 'toll_booth', 'app/images/josm/vehicle/toll_booth.png', 20, 9);
        OSM.Style.Utils.addStrokeArea(styleMap, 'barrier', 'wall', '#F0F050', '3');
        OSM.Style.Utils.addPoint(styleMap, 'barrier', 'lift_gate', 'app/images/josm/vehicle/lift_gate.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'barrier', 'cycle_barrier', 'app/images/josm/vehicle/cycle_barrier.png', 16, 14);
        OSM.Style.Utils.addStrokeArea(styleMap, 'barrier', 'fence', '#F0F050', '3');
        OSM.Style.Utils.addPoint(styleMap, 'barrier', 'fence', 'app/images/josm/misc/no_icon.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'barrier', 'turnstile', 'app/images/josm/vehicle/turnstile.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'barrier', 'stile', 'app/images/josm/vehicle/stile.png', 12, 12);
        OSM.Style.Utils.addStrokeArea(styleMap, 'barrier', 'hedge', '#F0F050', '3');
        OSM.Style.Utils.addPoint(styleMap, 'barrier', 'gate', 'app/images/josm/vehicle/gate.png', 16, 11);
        OSM.Style.Utils.addStroke(styleMap, 'barrier', 'bollard', '#F0F050', 7, 'dash');
        OSM.Style.Utils.addPoint(styleMap, 'barrier', 'bollard', 'app/images/josm/vehicle/restriction/bollard.png', 16, 16);
        OSM.Style.Utils.addPoint(styleMap, 'barrier', '*', 'app/images/josm/vehicle/restriction/barrier.png', 16, 16);

        OSM.Style.Utils.addSubStroke(styleMap, 'highway', '*', 'embankment', '*', '#ff0000', 5, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'railway', '*', 'embankment', '*', '#ff0000', 5, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'waterway', '*', 'embankment', '*', '#ff0000', 5, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'highway', '*', 'cutting', '*', '#ff0000', 5, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'railway', '*', 'cutting', '*', '#ff0000', 5, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'waterway', '*', 'cutting', '*', '#ff0000', 5, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'highway', '*', 'tunnel', '*', '#ff0000', 5, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'railway', '*', 'tunnel', '*', '#ff0000', 5, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'waterway', '*', 'tunnel', '*', '#ff0000', 5, 'dash');
        OSM.Style.Utils.addSubPoint(styleMap, 'highway', '*', 'bridge', 'swing', 'app/images/josm/vehicle/viaduct.png', 16, 16);
        OSM.Style.Utils.addSubPoint(styleMap, 'railway', '*', 'bridge', 'swing', 'app/images/josm/vehicle/viaduct.png', 16, 16);
        OSM.Style.Utils.addSubPoint(styleMap, 'waterway', '*', 'bridge', 'swing', 'app/images/josm/vehicle/viaduct.png', 16, 16);
        OSM.Style.Utils.addSubPoint(styleMap, 'highway', '*', 'bridge', 'aqueduct', 'app/images/josm/nautical/aqueduct.png', 16, 16);
        OSM.Style.Utils.addSubPoint(styleMap, 'railway', '*', 'bridge', 'aqueduct', 'app/images/josm/nautical/aqueduct.png', 16, 16);
        OSM.Style.Utils.addSubPoint(styleMap, 'waterway', '*', 'bridge', 'aqueduct', 'app/images/josm/nautical/aqueduct.png', 16, 16);
        OSM.Style.Utils.addSubPoint(styleMap, 'highway', '*', 'bridge', 'viaduct', 'app/images/josm/vehicle/viaduct.png', 16, 16);
        OSM.Style.Utils.addSubPoint(styleMap, 'railway', '*', 'bridge', 'viaduct', 'app/images/josm/vehicle/viaduct.png', 16, 16);
        OSM.Style.Utils.addSubPoint(styleMap, 'waterway', '*', 'bridge', 'viaduct', 'app/images/josm/vehicle/viaduct.png', 16, 16);
        OSM.Style.Utils.addSubStroke(styleMap, 'highway', '*', 'bridge', '*', '#ff0000', 5, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'railway', '*', 'bridge', '*', '#ff0000', 5, 'dash');
        OSM.Style.Utils.addSubStroke(styleMap, 'waterway', '*', 'bridge', '*', '#ff0000', 5, 'dash');
        OSM.Style.Utils.addSubPoint(styleMap, 'highway', '*', 'bridge', '*', 'app/images/josm/vehicle/viaduct.png', 16, 16);
        OSM.Style.Utils.addSubPoint(styleMap, 'railway', '*', 'bridge', '*', 'app/images/josm/vehicle/viaduct.png', 16, 16);
        OSM.Style.Utils.addSubPoint(styleMap, 'waterway', '*', 'bridge', '*', 'app/images/josm/vehicle/viaduct.png', 16, 16);

        return styleMap;
    }
}
